{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ default "k8sgpt" .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8sgpt-operator
    app.kubernetes.io/part-of: k8sgpt-operator
    {{- include "chart.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}

