apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: gpt-3.5-turbo
    backend: openai
    secret:
      name: k8sgpt-sample-secret
  remoteCache:
    interplex:
      endpoint: release-interplex-service:8084
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.49
