apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample-localai
  namespace: k8sgpt-operator-system
spec:
  model: ggml-gpt4all-j-v1.3-groovy.bin
  backend: localai
  baseUrl: http://local-ai.local-ai.svc.cluster.local:8080/v1
  noCache: false
  enableAI: true
  version: v0.3.0
  # if not specified, k8s will marshal as a zero-valued SecretRef, which causes errors
  secret: null