apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample-localai
  namespace: k8sgpt-operator-system
spec:
  ai:
    model: ggml-gpt4all-j-v1.3-groovy.bin
    backend: localai
    baseUrl: http://local-ai.local-ai.svc.cluster.local:8080/v1
    noCache: false
    enable: true
    version: v0.3.0